workfloworchestrator/orchestrator-ui-library

.gitignore, README.md, link-start.sh, link-stop.sh, package.json, yarn.lock
Setup to use Yalc as a tool to be able to work on the GPL component library and the Surf app implemation locally at the same time
X Add/Update documentation.
=> gitlab-19: Use yalc to support local development on gpl lib and surf app at the same time

.changeset/wild-walls-destroy.md, apps/wfo-ui/next.config.js, package.json, packages/eslint-config-custom/package.json
The changes made in this PR should make it possible to just copy the app and run it standalone.
- Eslint was missing in the eslint package, moved it from the root-package.json to the config package
- Running stanalone requires the transpile prop to be populated in the nextjs config
=> 110 updates eslint package

apps/wfo-ui/components/Metadata/Products/Products.tsx, apps/wfo-ui/components/Metadata/Products/productsQuery.ts, apps/wfo-ui/pages/metadata/productblocks.tsx, apps/wfo-ui/pages/metadata/products.tsx, apps/wfo-ui/utils/queryVarsMappers.ts, packages/orchestrator-ui-components/src/components/Table/utils/constants.ts, packages/orchestrator-ui-components/src/graphqlQueries/index.ts, packages/orchestrator-ui-components/src/graphqlQueries/productBlocksQuery.ts, packages/orchestrator-ui-components/src/hooks/useDataDisplayParams.ts, packages/orchestrator-ui-components/src/index.ts, packages/orchestrator-ui-components/src/messages/en-US.json, packages/orchestrator-ui-components/src/pages/index.ts, packages/orchestrator-ui-components/src/pages/metadata/ProductBlocksPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WFOMetadataPageLayout.tsx, packages/orchestrator-ui-components/src/pages/metadata/WFOProductBlocksPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/index.ts, packages/orchestrator-ui-components/src/types.ts
Creates the metadata product blocks page and move the page from the app into the package. 
Contains changes to the metadata product page that are part of one of these tickets but are added here to make the commit hoooks pass:
Productspage: https://github.com/workfloworchestrator/orchestrator-ui/issues/150
Fixed inputs: https://github.com/workfloworchestrator/orchestrator-ui/issues/88
- NA: Add/Update documentation.
- NA: Update CHANGELOG.md.
- NA: Affected functionality covered by system tests.
=> 86 metadata productblocks page

.changeset/README.md, .changeset/modern-olives-eat.md, .github/workflows/publish-to-npm.yml, README.md, package.json, packages/orchestrator-ui-components/CHANGELOG.md, packages/orchestrator-ui-components/package.json
https://github.com/workfloworchestrator/orchestrator-ui/issues/110
Using the Changesets github action combined with the changeset-bot.
1) Include a changeset in any PR towards main branch
2) When the main branch contains a changeset-file, changeset-bot opens a PR processing the version bumps to the package.json files
3) Afther merging that last PR, the bumped packages will be published to NPM
=> 110 Streamlines release process

packages/orchestrator-ui-components/src/components/WFOKeyValueTable/WFOKeyValueTable.tsx, packages/orchestrator-ui-components/src/components/WFOTable/WFOBasicTable/WFOBasicTable.tsx, packages/orchestrator-ui-components/src/components/WFOTable/WFOBasicTable/WFOSortDirectionIcon.tsx, packages/orchestrator-ui-components/src/components/WFOTable/WFOBasicTable/WFOTableHeaderCell.tsx, packages/orchestrator-ui-components/src/components/WFOTable/WFOBasicTable/index.ts, packages/orchestrator-ui-components/src/components/WFOTable/WFOTableWithFilter/WFOTableWithFilter.tsx, packages/orchestrator-ui-components/src/components/WFOTable/index.ts, packages/orchestrator-ui-components/src/components/WFOTable/utils/columns.ts
#211 
Changes in story #211 introduced a few console errors due to passing too many props to the table component of EUI.
This PR solves that issue, added a comment in the code why not to spread the column config and fixes another console error due to a missing key when mapping from an array to the key-value components.
Besides the fixes there is a small refactor and rename of the internal components of the WFOTable component
=> 211 fix render details console error

package.json, packages/orchestrator-ui-components/package.json, packages/orchestrator-ui-components/tsconfig.build.json
This PR introduces a specific build tsconfig in the orchestrator. It resolves the go-to issue when clicking from the app on a component to go right to the source code in the package instead of its dist folder.
While running the dev-server it still depends on the dist folders, which is desired.
Building the packages in the prepare script is need to prevent welcoming the developer with all kinds of not-found errors.
=> 218 multiple tsconfigs

packages/orchestrator-ui-components/src/components/WFOTable/WFOBasicTable/WFOBasicTable.tsx, packages/orchestrator-ui-components/src/components/WFOTable/WFOBasicTable/styles.ts
Some adjustments to make the table style match better with the design
- gray background table header
- slightly darker hover effect for the rows
- center vertically content in cells
=> WFO Table style update

packages/orchestrator-ui-components/src/components/WFOKeyValueTable/WFOKeyCell.tsx, packages/orchestrator-ui-components/src/components/WFOKeyValueTable/WFOValueCell.tsx, packages/orchestrator-ui-components/src/components/WFOKeyValueTable/styles.ts
Some style fixes for keyValue table
Note: the font weight of the key is not matching the design. Using "semibold" instead of "medium". Using "medium" does not result in a visible difference between the keys and values in the table.
=> Updates padding value and adds styles specific for key and value cells

packages/orchestrator-ui-components/src/pages/processes/tabConfig.ts
#345 
Applies always-on filter on process list page
=> 345 - Applies always-on filter on process list page

apps/wfo-ui-surf/package.json, apps/wfo-ui/package.json, package.json
Hot reloading was not working anymore. This is a quickfix to start working again. Both apps will always run while developing. Not expecting performance issues on local dev, because the actual compiling kicks in when visiting the page.
=> Fix for hot reloading

packages/orchestrator-ui-components/src/components/WFOWorkflowSteps/WFOWorkflowStepList/WFOStepListHeader.tsx
#318 
Hides the collapseAll button when the raw json is visible
=> 318 - Hides the collapseAll button when the raw json is visible

packages/orchestrator-ui-components/src/components/WfoBadges/WfoEngineStatusBadge/WfoEngineStatusBadge.tsx, packages/orchestrator-ui-components/src/components/WfoBadges/WfoFailedTasksBadge/WfoFailedTasksBadge.tsx, packages/orchestrator-ui-components/src/messages/en-US.json, packages/orchestrator-ui-components/src/messages/nl-NL.json
* Fixes the failed task banner icon to green (success) when no failed tasks are found
* Fixes the engineer banner icon to red (danger), when the engine is not running, but pausing or paused
=> 366 failedtask engine badge

packages/orchestrator-ui-components/src/graphqlQueries/resourceTypesQuery.ts, packages/orchestrator-ui-components/src/messages/en-US.json, packages/orchestrator-ui-components/src/messages/nl-NL.json, packages/orchestrator-ui-components/src/pages/metadata/WfoResourceTypesPage.tsx, packages/orchestrator-ui-components/src/types/types.ts
added `used in product blocks` column to Resource type table
=> add PB column to RT metadata table

.github/dependabot.yml, .github/workflows/lint-test-build.yml, .github/workflows/publish-to-npm.yml, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscription.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionDetailTree.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionProductBlock.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/styles.ts, packages/orchestrator-ui-components/src/components/WfoSubscription/utils/utils.tsx, packages/orchestrator-ui-components/src/components/WfoTree/WfoTreeNode.tsx, packages/orchestrator-ui-components/src/components/WfoTree/treeUtils.spec.ts, packages/orchestrator-ui-components/src/contexts/TreeContext.tsx, packages/orchestrator-ui-components/src/graphqlQueries/subscriptionDetailQuery.ts, packages/orchestrator-ui-components/src/messages/en-US.json, packages/orchestrator-ui-components/src/messages/nl-NL.json, packages/orchestrator-ui-components/src/stories/Button.jsx, packages/orchestrator-ui-components/src/stories/Configure.mdx, packages/orchestrator-ui-components/src/stories/Header.jsx, packages/orchestrator-ui-components/src/stories/Page.jsx, packages/orchestrator-ui-components/src/stories/button.css, packages/orchestrator-ui-components/src/stories/colors.mdx, packages/orchestrator-ui-components/src/stories/header.css, packages/orchestrator-ui-components/src/stories/page.css, packages/orchestrator-ui-components/src/types/types.ts, packages/orchestrator-ui-components/src/utils/getTokenName.ts, packages/orchestrator-ui-components/src/utils/string.spec.ts, packages/orchestrator-ui-components/src/utils/strings.ts
Implementation for https://github.com/workfloworchestrator/orchestrator-ui/issues/282
NOTE: we might want to broaden our linting rules: the last commit contains the results from: `yarn prettier --write .` : which also linted some .jsx stories...
=> Honor tree order and started working on hiding keys

.changeset/little-ducks-guess.md
This is a test release to be a baseline for the next change in this ticket: moving to absolute imports
=> 414 - Release before moving to absolute imports

.prettierrc, apps/wfo-ui-surf/pages/_app.tsx, apps/wfo-ui-surf/tsconfig.json, apps/wfo-ui/pages/_app.tsx, apps/wfo-ui/tsconfig.json, packages/orchestrator-ui-components/src/components/WfoAuth/WfoAuth.tsx, packages/orchestrator-ui-components/src/components/WfoStartPage/WfoListItemStartPage.tsx, packages/orchestrator-ui-components/src/components/WfoStartPage/WfoListStartPage.tsx, packages/orchestrator-ui-components/src/components/WfoStartPage/WfoMultiListSection.tsx, packages/orchestrator-ui-components/src/components/WfoStartPage/WfoNewProcessPanel.tsx, packages/orchestrator-ui-components/src/components/WfoStartPage/WfoStatCards.tsx, packages/orchestrator-ui-components/tsconfig.build.json, packages/orchestrator-ui-components/tsconfig.json
#414 
- Adds absolute imports in tsconfig for wfo-ui, wfo-ui-surf and orchestrator-ui-components
- Adds prettier rule to place the @/.... under the library imports as a separate group
- Fixes all imports in wfo-ui
- Fixes imports in _app.tsx for wfo-ui-surf
- Fixes imports in WfoStartPage components in orchestrator-ui-components
=> 414 absolute imports

.changeset/popular-dragons-flow.md, packages/eslint-config-custom/package.json
#414 
The eslint-config-custom package is used as a devDependency. The dependencies inside the eslint-config-custom should be in the dependencies section to be installed by a consumer of that package
=> 414 - Moves all devDependencies into the dependencies section

packages/orchestrator-ui-components/src/components/WfoForms/UserInputForm.tsx, packages/orchestrator-ui-components/src/components/confirmationDialog/WfoConfirmationDialog.tsx, packages/orchestrator-ui-components/src/messages/en-GB.json, packages/orchestrator-ui-components/src/messages/nl-NL.json
#435 #557 
- Adds confirm dialog when jumping back 1 step in forms
- Makes the leave-page-question overridable (without breaking existing implementations)
=> 435 Adds confirmation dialog when navigating a step back in the form

apps/wfo-ui/pages/_app.tsx
This closes https://github.com/workfloworchestrator/orchestrator-ui/issues/545 and https://github.com/workfloworchestrator/orchestrator-ui/issues/542
The keepPreviousData property seems to solve the problem of loading state when fetching additional pages. It keeps the data until the new data is loaded. Removing stale time makes sure data for a subscription is refreshed after a modify workflow is triggered solving 542. There are probably more fine grained and elegant solutions here but since we will have other tickets dealing with state and data retrieval is thought it was best to make a minimal fix here.
=> 545: Change default caching behaviour

.changeset/shaggy-squids-kick.md, apps/wfo-ui-surf/components/WfoServiceTicketDetailPage/WfoImpactedCustomersTable.tsx, apps/wfo-ui-surf/components/WfoServiceTicketsList/WfoServiceTicketsList.tsx, packages/orchestrator-ui-components/src/components/WfoSettings/WfoModifySettings.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoRelatedSubscriptions.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionDetailTree.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionProductBlock.tsx, packages/orchestrator-ui-components/src/components/WfoTree/WfoTreeNode.tsx, packages/orchestrator-ui-components/src/contexts/TreeContext.tsx
- Change tree icon of root PB
- Use title for root PB in tree instead of PB name
- At page load the root PB is expanded in card view
=> 536 change tree icon default expanded

.changeset/sixty-hounds-mix.md, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStep/WfoStep.tsx, packages/orchestrator-ui-components/src/types/types.ts
#598 
- A step contraining html was not considered as step content -- now it does
- Bonus: a json output was shown above the email when hiddenKey was enabled
=> 598 Fixes invisible email in step list

.changeset/eight-wolves-rhyme.md, .prettierignore, packages/orchestrator-ui-components/src/components/WfoProcessList/WfoProcessesList.tsx, packages/orchestrator-ui-components/src/components/WfoProcessList/processListObjectMappers.ts, packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/WfoSubscriptionsList.tsx, packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/index.ts, packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/subscriptionListTabs.ts, packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/subscriptionResultMappers.ts, packages/orchestrator-ui-components/src/components/WfoTable/WfoTableWithFilter/WfoTableWithFilter.tsx, packages/orchestrator-ui-components/src/configuration/constants.ts, packages/orchestrator-ui-components/src/hooks/useQueryWithGraphql.ts, packages/orchestrator-ui-components/src/messages/en-GB.json, packages/orchestrator-ui-components/src/messages/nl-NL.json, packages/orchestrator-ui-components/src/pages/metadata/WfoProductBlocksPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoProductsPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoResourceTypesPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoWorkflowsPage.tsx, packages/orchestrator-ui-components/src/utils/csvDownload.ts, packages/orchestrator-ui-components/src/utils/getQueryVariablesForExport.spec.ts, packages/orchestrator-ui-components/src/utils/getQueryVariablesForExport.ts, packages/orchestrator-ui-components/src/utils/index.ts, packages/orchestrator-ui-components/src/utils/sortObjectKeys.spec.ts, packages/orchestrator-ui-components/src/utils/sortObjectKeys.ts
#544 
- Export functionality to export the data from data list pages (subscription list page etc)
- Respects the set filters, but always fetches the first 1000 records
- Always exports all columns available on the page
- Places the export helper funtions in a util file
- Adds a lazy data fetch hook for graphql data -- this prevents that these 1000 records are being fetched on page load.
- not implementing the onExportData prop of the WfoTableWithFilter results in not rendering the Export button to make the export functionality optional
=> 544 table export

packages/orchestrator-ui-components/src/components/WfoForms/formFields/OrganisationField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/SubscriptionField.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionGeneral.tsx, packages/orchestrator-ui-components/src/graphqlQueries/customersQuery.ts, packages/orchestrator-ui-components/src/graphqlQueries/subscriptionDetailQuery.ts, packages/orchestrator-ui-components/src/graphqlQueries/subscriptionsDropdownOptionsQuery.ts, packages/orchestrator-ui-components/src/types/types.ts
Backend changes have caused properties rename in graphql. This PR changes the fieldnames on the frontend
=> 657 customer fieldname change

.changeset/popular-carrots-change.md, apps/wfo-ui-surf/pages/_app.tsx, apps/wfo-ui/pages/_app.tsx, package-lock.json, packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/WfoSubscriptionsList.tsx, packages/orchestrator-ui-components/src/components/WfoTable/WfoBasicTable/WfoBasicTable.tsx, packages/orchestrator-ui-components/src/messages/en-GB.json, packages/orchestrator-ui-components/src/messages/nl-NL.json, packages/orchestrator-ui-components/src/pages/metadata/WfoProductBlocksPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoProductsPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoResourceTypesPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoWorkflowsPage.tsx
Removal of keepPreviousData: when this was enabled the second page would still show data from page 1 until the data is fetched. This might confuse the user.
Switched from isLoading to isFetching: isFetching is, in contrast with isLoading, `true` when data gets refetched from the backend.
Added messages for the `no-data` state of the table: we distinguish now between "no data, because data is loading" and "no results found"
=> Fixes loading state for all tables. Removes keepPreviousData.

.github/workflows/publish-to-npm.yml
There are two depended actions, one that builds the package and pushes it to NPM and creates a tag, and one that reacts on that tag to create a tag in the example-orchestrator-ui to trigger a build of a new container in that repository with the just published new NPM package. But GitHub does not allow to trigger an action from another action, probably to prevent possible trigger loops. A way to circumvent this restriction is to use a Personal Access Token to create the first tag. The easiest solution is to use the same PAT that is also used to create the second tag.
=> use PAT instead of GITHUB_TOKEN to trigger tag example-orchestrator-ui action

.changeset/long-carrots-kneel.md, packages/eslint-config-custom/index.js, packages/eslint-config-custom/package.json
Remove turbo as standard extend option for eslint configurations so builds usingt this package wont fail if they dont use turbo
=> 719: Remove turbo eslint rules so downstream pacakges dont fail them

.changeset/silent-cameras-deliver.md, packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetailPage.tsx
- change process const to state var in WfoProcessDetailPageProps and check with lastStatus or lastStep is different if the process actually needs an update.
Fixes: #685, #650
=> 685: Fix form reloading and resetting inputs

.changeset/fresh-frogs-matter.md, packages/orchestrator-ui-components/src/components/WfoForms/formFields/utils.spec.ts, packages/orchestrator-ui-components/src/components/WfoForms/formFields/utils.ts, packages/orchestrator-ui-components/src/hooks/surf/useGetSubscriptionDropdownOptions.ts
- aggsp's have a portMode of `tagged` but it has a linkmember port which has a portMode `link_member` which is taken last in the reduce and becomes the value. I added a check if the portMode isn't set yet in the reduce.
- default status filter needs to be `active` for `useGetSubscriptionDropdownOptions`.
Closes: #651
=> 651: Fix incorrect port select options

.github/workflows/publish-to-npm.yml, .github/workflows/tag-example-ui.yml
Use a GitHub app on the workflow orchestrator organisation with Content and Metadata access to generate tokens that have access to the orchestrator-ui-library and example-orchestrator-ui repositories. This way there is no need to use personal access tokens, and the creation of a tag can trigger another workflow in the same repository.
=> use GitHub app generated token for repository access

.changeset/old-fishes-fold.md, packages/orchestrator-ui-components/src/components/WfoForms/AutoFieldLoader.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ConnectedSelectField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/CustomerField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ImsNodeIdField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListSelectField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/LocationCodeField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ProductField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/SelectField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/index.ts
The selectField has a connected and unconnected version. When a SelectField is called from another field that
is connected it can cause errors as described here: https://github.com/workfloworchestrator/orchestrator-ui-library/issues/681.  When called directly it will still need the props that the connectField function provides so it has a connected version as well.
=> 681 Create a connected and an unconnect SelectField

.changeset/four-pianos-destroy.md, packages/eslint-config-custom/package.json
Consuming projects will not receive the rules from @typescript-eslint/eslint-plugin when it is placed in devDependencies
=> Moves @typescript-eslint/eslint-plugin back to dependencies

.changeset/fair-cougars-grab.md, packages/orchestrator-ui-components/src/api/index.ts, packages/orchestrator-ui-components/src/api/types.ts, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ProductField.tsx
#812 
Note:
Had to introduce a type especially for the rest call for products. Compared to the GraphQL calls, the REST call returns objects with properties in snake_case. Since this type is very specific I prefixed it with `Legacy` and placed it next to the axios client in the code.
=> 812 Adds Product type specifically for REST call for fetching Products

packages/orchestrator-ui-components/src/components/index.ts, packages/orchestrator-ui-components/src/messages/en-GB.json, packages/orchestrator-ui-components/src/pages/metadata/WfoMetadataPageLayout.tsx, packages/orchestrator-ui-components/src/pages/metadata/index.ts, packages/orchestrator-ui-components/src/pages/subscriptions/WfoSubscriptionDetailPage.tsx, packages/orchestrator-ui-components/src/pages/subscriptions/WfoSubscriptionsListPage.tsx, packages/orchestrator-ui-components/src/pages/workflows/index.ts
Ticket: https://github.com/workfloworchestrator/orchestrator-ui-library/issues/596
Makes components exportable that are needed to be able to fork all toplevel pages in the app.
See this PR in the example app for a version were all pages are forked: https://github.com/workfloworchestrator/example-orchestrator-ui/pull/17
=> 596 forkable pages

.changeset/serious-cooks-leave.md, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionGeneral.tsx
#332
Metadata is not always available, therefore hiding the Metadata section on the SubscriptionDetail>General page when there is no data
=> 332 Hides the metadata section when no data is available

.changeset/odd-lobsters-eat.md, .changeset/silver-ears-jump.md, packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/WfoMenuLink.tsx, packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/WfoSidebar.tsx, packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/index.ts, packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/styles.ts
Ticket: https://github.com/workfloworchestrator/orchestrator-ui-library/issues/905
Improves sideNav functionality by
- Preventing a page reload when clicking on Metadata
- Keeping standard navigating behaviour like middle mouse click/command click opening a link in another tab in the background by using a link instead of an onclick handler.
There is a small difference in how the menu item renders when it's selected now that I still have to discuss with @wouter1975
=> 905: Improve sideBar menu functionality

.changeset/dull-tables-poke.md, package-lock.json, packages/orchestrator-ui-components/src/components/WfoForms/CreateForm.tsx, packages/orchestrator-ui-components/src/components/WfoForms/UserInputFormWizardDeprecated.tsx, packages/orchestrator-ui-components/src/components/WfoForms/index.ts, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStep/WfoStepForm.tsx, packages/orchestrator-ui-components/src/hooks/DataFetchHooks.ts, packages/orchestrator-ui-components/src/pages/processes/WfoStartProcessPage.tsx, packages/orchestrator-ui-components/src/rtk/api.ts
Renamed the old UserInputFormWizard to UserInputFormWizardDeprecated which uses the axios apiClient. The new one is currently used with CIM forms.
=> Deprecate axios version of UserInputFormWizard and useFilterQueryWithRest

packages/orchestrator-ui-components/src/components/WfoForms/formFields/SubscriptionField.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/utils/utils.ts, packages/orchestrator-ui-components/src/types/types.ts
#912 
Partially part of mentioned story. FieldValue in general can be `null`. Updated the type and added null checks
=> 912 Adds to the type of the FieldValue type

.changeset/ten-scissors-hide.md, packages/orchestrator-ui-components/src/pages/startPage/WfoStartPage.tsx, packages/orchestrator-ui-components/src/pages/startPage/useStartPageSummaryCardConfigurationOverride.ts, packages/orchestrator-ui-components/src/rtk/slices/orchestratorComponentOverride.ts
#879 
Makes summary cards on the start page overridable
=> 879 overridable summarycards

.changeset/ninety-stingrays-flash.md, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoInUseByRelations.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionProductBlock/WfoSubscriptionProductBlock.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/styles.ts, packages/orchestrator-ui-components/src/rtk/endpoints/index.ts, packages/orchestrator-ui-components/src/rtk/endpoints/subscriptionInUseByRelationsList.ts, packages/orchestrator-ui-components/src/types/types.ts
Replaces the jsonCode block output for the inUse by subscrtiptiosn field of the product block instance cards on the subscriptionDetail page
This is a possible follow up ticket that moves this functionality back to the backend: https://github.com/workfloworchestrator/orchestrator-ui-library/issues/1031
=> 776 in use by relations

.changeset/nine-buttons-poke.md, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListAddField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListDelField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/deprecated/VlanField.tsx, packages/orchestrator-ui-components/src/rtk/endpoints/subscriptionInUseByRelationsList.ts
https://github.com/workfloworchestrator/orchestrator-ui-library/issues/780 
The tickets describes shows the message that shows is different than in V1. The real fix IMO and the one implemented in this PR is to not show a message in a all until a port subscription is selected.
=> 780 vlan validator message

.changeset/sour-bears-fold.md, packages/orchestrator-ui-components/src/components/WfoBadges/WfoWebsocketStatusBadge/WfoWebsocketStatusBadge.tsx, packages/orchestrator-ui-components/src/components/WfoDiff/WfoDiff.tsx, packages/orchestrator-ui-components/src/components/WfoDiff/styles.ts, packages/orchestrator-ui-components/src/components/WfoSettings/WfoFlushSettings.tsx, packages/orchestrator-ui-components/src/components/WfoSettings/WfoModifySettings.tsx, packages/orchestrator-ui-components/src/components/WfoSettings/WfoStatus.tsx, packages/orchestrator-ui-components/src/components/WfoSettings/styles.ts, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionProductBlock/styles.ts, packages/orchestrator-ui-components/src/components/WfoSubscription/styles.ts, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStep/WfoStep.tsx, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStepStatusIcon/WfoStepStatusIcon.tsx, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/styles.ts, packages/orchestrator-ui-components/src/pages/settings/WfoSettingsPage.tsx
#626 
Small adjustments for dark theme in -detail pages. Forms are not in scope of this PR. That would be the next one
Delta view:
Settings:
Icons of product blocks:
Workflow detail:
=> 626 dark theme 2

.changeset/poor-pumpkins-cry.md, turbo.json
**Issue**:
The authorization scopes for OAuth are currently hardcoded in the NextAuth.js configuration, limiting operational flexibility across different environments.
Link to the issue: https://github.com/workfloworchestrator/orchestrator-ui-library/issues/1055
=> Configurable OAuth Scopes via Environment Variables

.changeset/shiny-trainers-juggle.md, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscription.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionDetailTree.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionProductBlock/WfoSubscriptionProductBlock.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionProductBlock/styles.ts, packages/orchestrator-ui-components/src/components/WfoTree/WfoTreeNode.tsx, packages/orchestrator-ui-components/src/components/WfoTree/styles.ts, packages/orchestrator-ui-components/src/components/WfoTree/treeUtils.spec.ts, packages/orchestrator-ui-components/src/hooks/useWithOrchestratorTheme.ts, packages/orchestrator-ui-components/src/types/types.ts
This ticket has to wait for https://github.com/workfloworchestrator/orchestrator-core/issues/626
Implements https://github.com/workfloworchestrator/orchestrator-ui-library/issues/367
Adds a different style if the productBlock instance is outside of the current subscription
=> 367 subscription productblocks outside the current subscription

.changeset/silly-candles-poke.md, packages/orchestrator-ui-components/src/components/WfoForms/formFields/deprecated/VlanField.tsx
#1066 
The Vlan field is depending on the subscription dropdown. When going to the second page, the choices from the first page should be shown in a "disabled" version of the field to remind the user what subscription and vlan were entered on the previous page. The disabled fields on the second page are still acting as active fields, they fetching subscriptions and the allowed vlans. Because of this fetching of available subscriptions, the vlan field was cleared.
This PR introduces a quick fix to prevent the vlan-field to clear the value when it is disabled.
=> 1066 Only allows to clear the value when the field is enabled

.changeset/seven-frogs-jam.md, .changeset/shy-rocks-help.md, packages/eslint-config-custom/index.js, packages/orchestrator-ui-components/src/contexts/OrchestratorConfigContext.tsx, packages/orchestrator-ui-components/src/rtk/storeProvider.tsx, packages/orchestrator-ui-components/src/utils/getEnvironmentVariables.spec.ts, packages/orchestrator-ui-components/src/utils/getEnvironmentVariables.ts, packages/orchestrator-ui-components/src/utils/index.ts
#1108 
- Updates the type of context providers to be possibly `null`. This is more realistic since the value is not available when the code runs in the browser context.
- Adds a helper function to retrieve multiple environment variables. The `getEnvironmentVariables` function aggregates all missing variables and logs a warning in the console if anything is missing.
=> 1108 fetch env vars with warnings

.changeset/shy-knives-relax.md, packages/orchestrator-ui-components/src/components/WfoProcessList/WfoProcessesList.tsx
While waiting for the conclusion of discussion in PR https://github.com/workfloworchestrator/orchestrator-ui-library/pull/1192
processing this quick-fix in the current PR to prevent glitchy behavior when data gets refreshed in Task list and Workfow list pages
=> Workflows tasks list loading state

.changeset/fresh-beans-brake.md, packages/orchestrator-ui-components/src/components/WfoForms/formFields/SummaryField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/deprecated/TimestampField.tsx
=> Fix 1239 text in form not visible

.changeset/little-poets-tap.md, packages/orchestrator-ui-components/src/components/WfoForms/formFields/deprecated/ImsPortIdField.tsx, packages/orchestrator-ui-components/src/hooks/deprecated/useGetSubscriptionDropdownOptions.ts, packages/orchestrator-ui-components/src/rtk/endpoints/metadata/workflows.ts
Update from the deprecated `-` separator to `|`
For devs more knowledgeable about this codebase than me, please check if there are other places where this might need to be updated.
=> Update gql filter separator to '|'

.changeset/proud-worms-tan.md, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListAddField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListDelField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListField.tsx, packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListItemField.tsx
#1294 
Partial rollback of https://github.com/workfloworchestrator/orchestrator-ui-library/pull/1279
The style changes are rolled back, the logic introduced in that PR are untouched
=> 1294 Rolling back the recent changes in the list fields

.changeset/shy-hotels-pretend.md, packages/orchestrator-ui-components/src/components/WfoForms/formFields/deprecated/ImsPortIdField.tsx, packages/orchestrator-ui-components/src/rtk/endpoints/formFields.ts
#1312
Enables refetching on mount to keep the ports list up to date
=> 1312 Enables refetching on mount to keep the ports list up to date

.changeset/gold-geese-divide.md, packages/orchestrator-ui-components/src/rtk/endpoints/subscriptionActions.ts
=> Fix workflow dropdown not refreshed after subscription is set in sync

.changeset/loud-apes-refuse.md, packages/orchestrator-ui-components/src/rtk/api.ts
I propose a NEXT_PUBLIC_DISABLE_CACHE enviroment variable here instead of adding it to the OrchestratorConfig type because:
- This should only be used in development mode scenarios
- The orchestratorConfig object is not available yet when the RTKQuery api is initialized and we need to set the keepUnusedDataFor property.
=> 874: Use NEXT_PUBLIC env to disable cache in development mode

.changeset/sharp-penguins-sleep.md, packages/orchestrator-ui-components/src/components/WfoSearchBar/WfoSearchField.tsx
#735 
- Triggers onUpdateQueryString when search field is erased.
- Adds queryIsValid prop (optional prop) -- it was hardcoded to true
=> 735 Triggers onUpdateQueryString when search field is erased

.changeset/smooth-lies-tease.md, packages/orchestrator-ui-components/src/utils/csvDownload.ts, packages/orchestrator-ui-components/src/utils/index.ts, packages/orchestrator-ui-components/src/utils/toObjectWithSerializedValues.spec.ts, packages/orchestrator-ui-components/src/utils/toObjectWithSerializedValues.ts
#1398 
- Implements a generic way of serializing objects when exporting CSV files
- added "date" objects as an exception to not serialize
=> 1398 serialize objects while exporting data

.changeset/quick-lamps-invent.md, package-lock.json, package.json, packages/jest-config/package.json, packages/orchestrator-ui-components/package.json, packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoPageHeader/styles.ts, packages/orchestrator-ui-components/src/components/WfoTitleWithWebsocketBadge/WfoTitleWithWebsocketBadge.tsx
Updates all minor version upgrades and some major. ElasticEUI updated to latest major version. This finally supports TS 5 so an override is removed. 
After this update a there are 2 `npm audit` warnings left
- cookie < v0.7 used in next-auth: this will be fixed upstream after this pr: https://github.com/nextauthjs/next-auth/pull/12046
- micromatch: this is part of the lodash version used in uniforms. Wont fix sinc
Some packages have major version upgrades that are moved to another ticket: https://github.com/workfloworchestrator/orchestrator-ui-library/issues/1500
=> 1487 updates all minor npm package versions and some major

.changeset/popular-apes-shop.md, packages/orchestrator-ui-components/src/components/WfoTable/WfoRowContextMenu/WfoRowContextMenu.tsx, packages/orchestrator-ui-components/src/components/WfoTable/WfoRowContextMenu/index.ts, packages/orchestrator-ui-components/src/components/WfoTable/index.ts, packages/orchestrator-ui-components/src/icons/WfoDotsHorizontal.tsx, packages/orchestrator-ui-components/src/icons/heroicons/WfoHeroIconsWrapper.tsx, packages/orchestrator-ui-components/src/icons/heroicons/WfoWrench.tsx, packages/orchestrator-ui-components/src/icons/heroicons/index.ts, packages/orchestrator-ui-components/src/rtk/endpoints/index.ts, packages/orchestrator-ui-components/src/rtk/endpoints/subscriptionActions.ts
#1402 
Adds context menu to be used in the table. It exposes a callback that is triggered when the menu opens (for optionally triggering a REST call to populate the menu)
Example usage:
=> 1402 table row context menu

.changeset/silent-plums-invite.md, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoInUseByRelations.tsx, packages/orchestrator-ui-components/src/components/WfoTable/WfoFirstPartUUID/WfoFirstPartUUID.tsx
#1561 
Fixes double copy icon in subscription detail page at the in-use-by-subscriptions section
=> 1561 Fixes double copy icon in subscription detail page at the in-use-by-subscriptions section

.changeset/eleven-islands-kiss.md, packages/orchestrator-ui-components/src/components/WfoForms/UserInputForm.tsx, packages/orchestrator-ui-components/src/contexts/WfoErrorMonitoringProvider.tsx, packages/orchestrator-ui-components/src/contexts/index.ts, packages/orchestrator-ui-components/src/hooks/index.ts, packages/orchestrator-ui-components/src/hooks/useWfoErrorMonitoring.ts, packages/orchestrator-ui-components/src/rtk/endpoints/streamMessages.ts
#692 
Adds a `WfoErrorMonitoringProvider` to be implemented in the wfo-ui app in `_app.tsx`.
It is providing a handler to report errors to remote logging / tracing (Sentry for example)
The `useWfoErrorMonitoring()` hook exposes 2 functions: `reportError` and `reportMessage`. The provider is introduced to not tightly couple to Sentry. Implementing the monitoring is optional. The `WfoErrorMonitoringProvider` does not need to be added to `_app.tsx`.
=> 692 Error monitoring

.changeset/clean-bags-visit.md, packages/orchestrator-ui-components/src/utils/uuid.spec.ts, packages/orchestrator-ui-components/src/utils/uuid.ts
This fixes the bug where an NMS chassis detail page in de Surf implementation of the app raises an unexpected error and causes the page to crash. The error is caused by because a result for retrieving the ports has a subscriptionId that is Null.
=> Fix type expected by uuid function

.changeset/slimy-points-press.md, packages/orchestrator-ui-components/src/components/WfoInsyncIcon/WfoInsyncIcon.tsx
#1623 
Changes the colors of the WfoInsyncIcon to make the no-in-sync state more prominent
=> 1623 Changes colors of WfoInsyncIcon

.changeset/swift-jars-exercise.md, packages/orchestrator-ui-components/src/components/WfoBadges/WfoProductBlockBadge/WfoProductBlockBadge.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoProductBlocksPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoProductsPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoResourceTypesPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoTasksPage.tsx, packages/orchestrator-ui-components/src/pages/metadata/WfoWorkflowsPage.tsx, packages/orchestrator-ui-components/src/utils/getQueryUrl.spec.ts, packages/orchestrator-ui-components/src/utils/getQueryUrl.ts, packages/orchestrator-ui-components/src/utils/index.ts
#289 
- Metadata page: making related product blocks, resource types and product tags badges clickable. It will update the search query to show that specific item.
- Adds helper util to construct the URL
=> 289 clickable badges on metadata page

.changeset/real-planets-bake.md, packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/WfoGroupedTable/WfoGroupedTable.tsx, packages/orchestrator-ui-components/src/types/types.ts, packages/orchestrator-ui-components/src/utils/csvDownload.ts
#1479 
Changes to support functionality in the SURF specific app but also useful for consumers of the library:
- GroupedTable: The table has a small header with a button "Collapse / Expand", this can now be overridden
- csvDownload: Changed the parameters of initiateCsvFileDownload for directly exporting data to CSV
- Introduced a utility type to help ensuring that all the props of an object will be of type "string". Typically useful for the csvDownload functionality
=> 1479 grouped table and csv download updates

.changeset/olive-balloons-yawn.md, packages/orchestrator-ui-components/src/rtk/endpoints/streamMessages.ts
For some users the toast becomes invisible and blocks the Next/Back buttons. Currently cannot reproduce the case where the toast becomes invisible, probably an issue with some browsers.
Discussed with @wouter1975, the current fix is to remove the toast list for failed websockets completely and possibly add the error message in the navbar or somewhere else where could be visible. [#1662](https://github.com/workfloworchestrator/orchestrator-ui-library/issues/1662)
=> Remove toast for failed WebSocket that covers the next button

.changeset/fuzzy-cherries-doubt.md, packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoPageTemplate/ContentContext.tsx, packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoPageTemplate/WfoPageTemplate.tsx, packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoPageTemplate/index.ts, packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoPageTemplate/styles.ts, packages/orchestrator-ui-components/src/components/WfoTimeline/WfoTimeline.tsx, packages/orchestrator-ui-components/src/components/WfoTimeline/WfoTimelineStep.tsx, packages/orchestrator-ui-components/src/components/WfoTimeline/styles.ts, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStep/WfoStep.tsx, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStepList/WfoStepList.tsx, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStepStatusIcon/WfoStepStatusIcon.tsx, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoWorkflowStepList/WfoStepListHeader.tsx, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/styles.ts, packages/orchestrator-ui-components/src/hooks/index.ts, packages/orchestrator-ui-components/src/hooks/useContentRef.ts, packages/orchestrator-ui-components/src/pages/processes/WfoStartProcessPage.tsx
#330 
- Making the timeline sticky at the top of the screen
- Introduces a ContentContext and a useContentRef to be used to easily refer to the reference of the scrollable content section. In this case used to call a `scrollBy(...)` on it.
=> 330 process detail sticky timeline

.changeset/lucky-otters-invite.md, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionProductBlock/WfoProductBlockKeyValueRow.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionProductBlock/WfoSubscriptionProductBlock.tsx, packages/orchestrator-ui-components/src/components/WfoSubscription/overrides/useSubscriptionDetailValueOverride.ts, packages/orchestrator-ui-components/src/rtk/slices/orchestratorComponentOverride.ts
In case consumers want to override values in the product block tables, the override function provides now a second parameter containing all key-values
=> 1635 Adds allFieldValues parameter for override function

.changeset/rude-starfishes-divide.md, packages/orchestrator-ui-components/src/components/WfoProcessList/WfoProcessesList.tsx, packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/WfoToolTip.tsx, packages/orchestrator-ui-components/src/messages/en-GB.json, packages/orchestrator-ui-components/src/messages/nl-NL.json, packages/orchestrator-ui-components/src/pages/processes/WfoProcessListSubscriptionsCell.tsx
#1210 
- Adds a badge with number of subscriptions not shown in the affected-subscriptions cell on the process list page
- The badge is always visible, the text left of it will get cut off in favor of the badge
=> 1210 workflow list table multiple subscriptions

.changeset/evil-roses-kick.md, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoWorkflowStepList/WfoWorkflowStepList.tsx
Fixes a regression in WfoProcessSubscriptionDelta.
Closes #2015
=> 2015 fix WfoProcessSubscriptionDelta not showing the old subscription

packages/orchestrator-ui-components/src/components/WfoForms/UserInputForm.tsx, packages/orchestrator-ui-components/src/components/WfoForms/UserInputFormWizard.tsx, packages/orchestrator-ui-components/src/components/WfoStartButton/WfoStartTaskComboBox.tsx, packages/orchestrator-ui-components/src/components/WfoStartButton/WfoStartWorkflowComboBox.tsx, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStep/WfoStep.tsx, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStep/WfoStepForm.tsx, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStepList/WfoStepList.tsx, packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoWorkflowStepList/WfoWorkflowStepList.tsx, packages/orchestrator-ui-components/src/messages/en-GB.json, packages/orchestrator-ui-components/src/messages/nl-NL.json, packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetail.tsx, packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetailPage.tsx, packages/orchestrator-ui-components/src/rtk/endpoints/processDetail.ts, packages/orchestrator-ui-components/src/rtk/endpoints/startOptions.ts, packages/orchestrator-ui-components/src/types/forms.ts, packages/orchestrator-ui-components/src/types/types.ts, packages/orchestrator-ui-components/src/utils/getProductNamesFromProcess.spec.ts, version-compatibility.json
Closes #2013 and #1730 
Depends on: https://github.com/workfloworchestrator/orchestrator-core/pull/990
Adds support for reflecting RBAC rules from the backend in the frontend. Depends on a backend update.
When a user lacks permission for an operation, buttons and input fields (if applicable) are grayed out
Unable to create specific products:
Unable to start a specific task:
Unable to resume a workflow:
Unable to run a specific workflow on a subscription:
=> Reflect RBAC rules from backend in GUI
