workfloworchestrator/orchestrator-ui-library

apps/example-orchestrator-ui/pages/_app.tsx
libs/orchestrator-ui-components/package.json
libs/orchestrator-ui-components/src/lib/components/OrchestratorPageTemplate/OrchestratorPageHeader.tsx
libs/orchestrator-ui-components/src/lib/components/OrchestratorPageTemplate/OrchestratorPageTemplate.tsx
libs/orchestrator-ui-components/src/lib/components/OrchestratorPageTemplate/OrchestratorSidebar.tsx

Removes the usage of nextjs dependency in the lib section.

Removing nextjs from lib

---

README.md

An initial approach to define some rules regarding which types are allowed in the lib, how we handle the generated types and a start for a naming convention.

Add typescript docs

---

apps/example-orchestrator-ui/pages/settings.tsx
libs/orchestrator-ui-components/src/lib/components/Breadcrumbs/BreadcrumbListPages.tsx
libs/orchestrator-ui-components/src/lib/components/OrchestratorPageTemplate/OrchestratorSidebar/OrchestratorSidebar.tsx
libs/orchestrator-ui-components/src/lib/components/SettingsPage/EngineStatusButton.tsx
libs/orchestrator-ui-components/src/lib/components/SettingsPage/FlushSettings.tsx
libs/orchestrator-ui-components/src/lib/components/SettingsPage/ModifySettings.tsx
libs/orchestrator-ui-components/src/lib/components/SettingsPage/Settings.tsx
libs/orchestrator-ui-components/src/lib/components/SettingsPage/Status.tsx
libs/orchestrator-ui-components/src/lib/components/SettingsPage/index.ts
libs/orchestrator-ui-components/src/lib/components/index.ts
libs/orchestrator-ui-components/src/lib/hooks/useEngineStatusQuery.ts
libs/orchestrator-ui-components/src/lib/types.ts
libs/orchestrator-ui-components/src/lib/utils/getTokenName.spec.ts

Settings page

---

apps/example-orchestrator-ui/pages/_app.tsx
libs/orchestrator-ui-components/package.json
libs/orchestrator-ui-components/src/lib/components/SettingsPage/FlushSettings.tsx
libs/orchestrator-ui-components/src/lib/hooks/DataFetchHooks.ts
libs/orchestrator-ui-components/src/lib/hooks/useEngineStatusQuery.ts
libs/orchestrator-ui-components/src/lib/types.ts

Added ability to flush cache and header -> engineStatus now toggles when engineStatus changes.

flush cache and other additions to settings page

---

apps/example-orchestrator-ui/pages/_app.tsx
libs/orchestrator-ui-components/src/lib/components/OrchestratorPageTemplate/OrchestratorPageTemplate/OrchestratorPageTemplate.tsx
libs/orchestrator-ui-components/src/lib/components/OrchestratorPageTemplate/OrchestratorSidebar/OrchestratorSidebar.tsx

In this MR:
- Add all menutitems from design. Unimplemented pages will 404
- Use router from nextjs directly instead of passing it down
- Highlight the route your on

90-left-menu: Add items

---

.changeset/rare-poems-whisper.md
.eslintrc.js
README.md
apps/wfo-ui/.eslintrc.js
apps/wfo-ui/components/searchBar.tsx
apps/wfo-ui/package.json
apps/wfo-ui/tsconfig.json
mkdocs/docs/adrs/0004-turbo-repo-and-dependencies.md
packages/eslint-config-custom/CHANGELOG.md
packages/eslint-config-custom/package.json
packages/jest-config/package.json
packages/orchestrator-ui-components/CHANGELOG.md
packages/orchestrator-ui-components/eslintrc.js
packages/orchestrator-ui-components/package.json
packages/orchestrator-ui-components/tsconfig.json
packages/tsconfig/CHANGELOG.md
packages/tsconfig/package.json
turbo.json
yarn.lock

Moved TSConfig / ESlint to separate packages.
@ricardovdheijden : can you create the new packages on npm? -> Then I can re-publish them

Standalone build

---

.changeset/nice-socks-tie.md
README.md
packages/jest-config/package.json
packages/tsconfig/package.json

https://github.com/workfloworchestrator/orchestrator-ui/issues/110
- Removes the private flag from the package.json files in the jest-config and tsconfig packages.
- Prepares release
- Updates Readme with some explanation what happens in every step in the changsets

110 Release jest-config and tsconfig packages

---

.github/workflows/publish-to-npm.yml

Status check, as a in between PR to get the manual trigger working in the project
https://github.com/workfloworchestrator/orchestrator-ui/issues/110

110 Adds workflow to check for any releases

---

.changeset/good-dancers-float.md
packages/orchestrator-ui-components/tsconfig.json

This should make the IDE find the non-transpiled files when consuming the ui package in the app in the monorepo

Updates tsconfig to define a root and out dir

---

packages/orchestrator-ui-components/tsconfig.json

Rolling back changes from : https://github.com/workfloworchestrator/orchestrator-ui/pull/195

Rolling back tsconfig adjustment

---

mkdocs/docs/adrs/0006-types-extended.md

A summary of things discussed and decided in the past weeks. A request for comment!

ADR Types proposal

---

packages/orchestrator-ui-components/src/graphqlQueries/processListQuery.ts
packages/orchestrator-ui-components/src/messages/en-US.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/pages/processes/WFOProcessListPage.tsx
packages/orchestrator-ui-components/src/pages/processes/tableConfig.ts
packages/orchestrator-ui-components/src/types/types.ts

#91 
- Renames lastStep to step
- adds workflowTarget
- Updates query

91 - Renames lastStep to step and adds workflowTarget

---

packages/orchestrator-ui-components/src/pages/metadata/WFOProductBlocksPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WFOProductsPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WFOResourceTypesPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WFOWorkflowsPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/tableConfig.ts

Added hidden columns, some uuid formatting, and column width.

hidden columns and formatting

---

packages/orchestrator-ui-components/src/components/WFOSubscriptionsList/WFOSubscriptionsList.tsx
packages/orchestrator-ui-components/src/components/WFOTable/WFOFirstPartUUID/WFOFirstPartUUID.tsx
packages/orchestrator-ui-components/src/components/WFOTable/WFOFirstPartUUID/index.ts
packages/orchestrator-ui-components/src/components/WFOTable/WFOTableWithFilter/WFOTableWithFilter.tsx
packages/orchestrator-ui-components/src/pages/metadata/WFOProductBlocksPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WFOProductsPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WFOResourceTypesPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WFOWorkflowsPage.tsx
packages/orchestrator-ui-components/src/pages/processes/WFOProcessListPage.tsx

#211 
- Fixes the unsorted key order in the detail view (in table component)
- Shortens UUIDs in tables
- Improves rendering multiple badges per cell in the detail view

211 detail view match key order table

---

apps/wfo-ui/package.json
apps/wfo-ui/pages/_app.tsx
apps/wfo-ui/pages/metadata/workflows.tsx
apps/wfo-ui/pages/subscriptions/[subscriptionId].tsx
packages/orchestrator-ui-components/package.json
packages/orchestrator-ui-components/src/components/WFOSubscription/WFOProcessesTimeline.tsx
packages/orchestrator-ui-components/src/components/WFOSubscription/WFOSubscriptionDetailTree.tsx
packages/orchestrator-ui-components/src/components/WFOSubscription/WFOSubscriptionGeneral.tsx
packages/orchestrator-ui-components/src/components/WFOTable/WFODataGridTable/WFODataGridTable.tsx
packages/orchestrator-ui-components/src/components/WFOTable/WFOTableWithFilter/WFOTableWithFilter.tsx
yarn.lock

Updating EUI to v 88.1.0.
- EuiLoadingContent was deprecated and, for now, replaced with WFOLoading
- One prop in the EuiTable/Grid became possibly undefined

Updates eui version to 88.1.0 and fixes breaking changes

---

packages/orchestrator-ui-components/src/components/WFOSteps/WFOStep/WFOStep.tsx
packages/orchestrator-ui-components/src/components/WFOSteps/WFOStepList/WFOStepList.tsx
packages/orchestrator-ui-components/src/components/WFOSteps/getStyles.ts
packages/orchestrator-ui-components/src/types/types.ts

Added:
- Email preview
- showHiddenKeys and showRawJSON
Note: I am not completely happy with the `filteredStepDelta` code. If you know an easy fix, please apply.

Mvp show email preview

---

apps/wfo-ui/constants.ts
apps/wfo-ui/pages/_app.tsx
packages/orchestrator-ui-components/src/components/WFOPageTemplate/WFOSidebar/WFOStartCreateWorkflowButtonComboBox.tsx
packages/orchestrator-ui-components/src/components/WFOProcessesList/WFOProcessList.tsx
packages/orchestrator-ui-components/src/components/WFOSubscriptionsList/WFOSubscriptionsList.tsx
packages/orchestrator-ui-components/src/contexts/OrchestratorConfigContext.tsx
packages/orchestrator-ui-components/src/hooks/useOrchestratorConfig.ts
packages/orchestrator-ui-components/src/hooks/useQueryWithGraphql.ts
packages/orchestrator-ui-components/src/pages/metadata/WFOProductBlocksPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WFOProductsPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WFOResourceTypesPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WFOWorkflowsPage.tsx
packages/orchestrator-ui-components/src/pages/processes/WFOProcessDetail.tsx
packages/orchestrator-ui-components/src/pages/processes/WFOProcessDetailPage.tsx
packages/orchestrator-ui-components/src/pages/workflow/WFOStartWorkflowPage.tsx
packages/orchestrator-ui-components/src/utils/environmentVariables.spec.ts
packages/orchestrator-ui-components/src/utils/environmentVariables.ts
packages/orchestrator-ui-components/src/utils/index.ts
turbo.json

#314 
- Removes useCoreConnection prop from useQueryWithGraphql
- Adds refetchInterval (disables when undefined)

314 process detail data polling

---

packages/orchestrator-ui-components/src/components/WFOInsyncIcon/WFOInsyncIcon.stories.tsx
packages/orchestrator-ui-components/src/components/WFOInsyncIcon/WFOInsyncIcon.tsx
packages/orchestrator-ui-components/src/components/WFOSubscription/SubscriptionKeyValueBlock.tsx
packages/orchestrator-ui-components/src/components/WFOSubscription/WFOSubscriptionActions.tsx
packages/orchestrator-ui-components/src/components/WFOSubscription/WFOSubscriptionGeneral.tsx
packages/orchestrator-ui-components/src/components/WFOSubscription/utils/utils.spec.ts
packages/orchestrator-ui-components/src/components/WFOSubscription/utils/utils.tsx
packages/orchestrator-ui-components/src/components/WFOSubscriptionsList/WFOSubscriptionsList.tsx
packages/orchestrator-ui-components/src/hooks/useSubscriptionActions.ts
packages/orchestrator-ui-components/src/messages/en-US.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/pages/subscriptions/WFOSubscriptionDetailPage.tsx

- Requirements from this ticket: https://github.com/workfloworchestrator/orchestrator-ui/issues/278
- Wouter's feedback on this ticket: https://github.com/workfloworchestrator/orchestrator-ui/issues/279

278 action buttons modal

---

apps/wfo-ui/pages/start-workflow/[workflowName].tsx
packages/orchestrator-ui-components/src/components/WFOButtonComboBox/WFOButtonComboBox.tsx
packages/orchestrator-ui-components/src/components/WFOButtonComboBox/styles.ts
packages/orchestrator-ui-components/src/components/WFOPageTemplate/WFOSidebar/WFOSidebar.tsx
packages/orchestrator-ui-components/src/components/WFOPageTemplate/WFOSidebar/WFOStartCreateWorkflowButtonComboBox.tsx
packages/orchestrator-ui-components/src/components/WFOStartTaskButtonComboBox/WFOStartTaskButtonComboBox.tsx
packages/orchestrator-ui-components/src/components/WFOStartTaskButtonComboBox/index.ts
packages/orchestrator-ui-components/src/components/index.ts
packages/orchestrator-ui-components/src/graphqlQueries/workflows/workflowsQueryForDropdownList.ts
packages/orchestrator-ui-components/src/messages/en-US.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/pages/tasks/WFOTaskListPage.tsx
packages/orchestrator-ui-components/src/pages/workflow/WFOStartWorkflowPage.tsx

Working start task dropdown + some translations for NL + Fix so menu works on mobile
Implements: https://github.com/workfloworchestrator/orchestrator-ui/issues/277

277 - Task dropdown

---

packages/orchestrator-ui-components/src/components/WFOPageTemplate/WFOSidebar/WFOSidebar.tsx
packages/orchestrator-ui-components/src/components/WFOStartTaskButtonComboBox/WFOStartTaskButtonComboBox.tsx

Handled last 2 comments of #277

---

packages/orchestrator-ui-components/src/components/WFOTable/WFOTableWithFilter/WFOTableWithFilter.tsx

Fixes missing clipboard icon
Also specified type to prevent issues in the future

Fixes missing clipboard icon

---

packages/orchestrator-ui-components/src/components/WFOProcessesList/WFOProcessList.tsx
packages/orchestrator-ui-components/src/pages/tasks/WFOTaskListPage.tsx

After reviewing task list table, I propose:
* a new ordering - more inline with process list table
* small change for default hidden columns
* and set some new column width

updated ordering task column, fixed column widths

---

packages/orchestrator-ui-components/src/graphqlQueries/productBlocksQuery.ts
packages/orchestrator-ui-components/src/messages/en-US.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/pages/metadata/WfoProductBlocksPage.tsx
packages/orchestrator-ui-components/src/types/types.ts

Added PB column to metadata PB table

---

packages/orchestrator-ui-components/src/components/WfoProcessesList/WfoProcessList.tsx

Adds esquery string as input for the table to populate the search field

81 Fix query from url in Processes and Tasks pages

---

packages/orchestrator-ui-components/src/components/WfoForms/AutoFieldLoader.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/RadioField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/index.ts

Migrated RadioField from v1 app. Replaced the standard html input with EUI components

337 - Adds RadioField

---

packages/orchestrator-ui-components/src/components/WfoBadges/WfoWorkflowTargetBadge/WfoWorkflowTargetBadge.tsx
packages/orchestrator-ui-components/src/components/WfoBadges/WfoWorkflowTargetBadge/index.ts
packages/orchestrator-ui-components/src/components/WfoProcessesList/WfoProcessList.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/utils/utils.spec.ts
packages/orchestrator-ui-components/src/components/WfoSubscription/utils/utils.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoWorkflowsPage.tsx
packages/orchestrator-ui-components/src/types/types.ts

- Applies badge style to TARGET in workflow metadata table
- Applies badge style to TARGET in process/task list table

401 use wftarget as coloured badge

---

packages/orchestrator-ui-components/src/components/WfoForms/AutoFieldLoader.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/OptGroupField.tsx
packages/orchestrator-ui-components/src/messages/en-US.json
packages/orchestrator-ui-components/src/messages/nl-NL.json

337 Adds OptGroupField

---

packages/orchestrator-ui-components/src/components/WfoForms/AutoFieldLoader.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/AcceptField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/AcceptFieldStyling.ts
packages/orchestrator-ui-components/src/components/WfoForms/formFields/index.ts
packages/orchestrator-ui-components/src/components/WfoTree/WfoTreeNode.tsx
packages/orchestrator-ui-components/src/components/WfoTree/styles.ts
packages/orchestrator-ui-components/src/contexts/ApiClientContext.tsx

337 - Adds AcceptField

---

.changeset/silent-cameras-sort.md

#414 Preparing release to test after introducing absolute paths

414 - Setup changeset

---

.changeset/clean-moose-add.md
apps/wfo-ui-surf/components/WfoServiceTicketDetailPage/WfoSubscriptionImpactTable.tsx
apps/wfo-ui-surf/pages/forms.tsx
apps/wfo-ui/pages/forms.tsx
packages/eslint-config-custom/index.js
packages/orchestrator-ui-components/src/api/index.ts
packages/orchestrator-ui-components/src/components/WfoForms/CreateForm.tsx
packages/orchestrator-ui-components/src/components/WfoForms/UserInputForm.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/IpPrefixTableField.tsx
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStepList/WfoStepList.tsx
packages/orchestrator-ui-components/src/pages/workflow/WfoStartWorkflowPage.tsx

#414 
- Only allowing console.error
- Fixes console logs in codebase
- Adds exceptions per case in current codebase

414 ban console log

---

packages/orchestrator-ui-components/src/components/WfoForms/UserInputForm.tsx
packages/orchestrator-ui-components/src/contexts/ConfirmationDialogProvider.tsx
packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetail.tsx
packages/orchestrator-ui-components/src/pages/tasks/WfoTaskListPage.tsx

Merging this one in an exising PR -- all modal related

435 Implements the back button in forms

---

packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/WfoStartCreateWorkflowButtonComboBox.tsx
packages/orchestrator-ui-components/src/components/WfoStartTaskButtonComboBox/WfoStartTaskButtonComboBox.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionActions.tsx
packages/orchestrator-ui-components/src/hooks/index.ts
packages/orchestrator-ui-components/src/hooks/useCheckEngineStatus.ts
packages/orchestrator-ui-components/src/hooks/useEngineStatusQuery.ts
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetail.tsx
packages/orchestrator-ui-components/src/pages/tasks/WfoTaskListPage.tsx

#415 
- Shows a toast message when the action cannot be performed.
- When the onClick happens a refetch is triggered in the useEngineStatus hook.
- As a bonus: the engine status at the top navigation will update too

415 engine not running warning

---

packages/orchestrator-ui-components/src/components/WfoProcessesList/WfoProcessList.tsx
packages/orchestrator-ui-components/src/components/WfoSearchBar/WfoSearchField.tsx
packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/WfoSubscriptionsList.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTableWithFilter/WfoTableWithFilter.tsx
packages/orchestrator-ui-components/src/graphqlQueries/processListQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/productBlocksQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/productsQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/relatedSubscriptionsQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/resourceTypesQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/subscriptionsListQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/workflows/workflowsQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/workflows/workflowsQueryForDropdownList.ts
packages/orchestrator-ui-components/src/pages/metadata/WfoProductBlocksPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoProductsPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoResourceTypesPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoWorkflowsPage.tsx
packages/orchestrator-ui-components/src/types/types.ts

#478 
- Implements query parameter to filter data in tables
- Filtering with table controls i NOT part of this PR. Will be implemented in a different PR

478 filter query backend

---

packages/orchestrator-ui-components/src/components/WfoSettingsPage/WfoFlushSettings.tsx
packages/orchestrator-ui-components/src/components/WfoStartPage/WfoListStartPage.tsx
packages/orchestrator-ui-components/src/hooks/DataFetchHooks.ts

Fixes a wrong react-query cache name for the flush cache apiCall and a small bug on the startPage.
closes #479

Fixes bug on settings and start page

---

packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionDetailTree.tsx
packages/orchestrator-ui-components/src/components/WfoTextAnchor/WfoTextAnchor.stories.tsx
packages/orchestrator-ui-components/src/components/WfoTextAnchor/WfoTextAnchor.tsx
packages/orchestrator-ui-components/src/components/WfoTextAnchor/index.ts
packages/orchestrator-ui-components/src/components/WfoTextAnchor/styles.ts
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoWorkflowStepList/WfoStepListHeader.tsx
packages/orchestrator-ui-components/src/components/index.ts
packages/orchestrator-ui-components/src/contexts/TreeContext.tsx
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json

Closes: https://github.com/workfloworchestrator/orchestrator-ui/issues/328

328 Show hide all product blocks on service configuration page

---

packages/orchestrator-ui-components/src/components/WfoProcessList/WfoProcessList.tsx
packages/orchestrator-ui-components/src/components/WfoSearchBar/WfoSearchField.tsx
packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/WfoSubscriptionsList.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTableWithFilter/WfoTableWithFilter.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTableWithFilter/updateQueryString.spec.ts
packages/orchestrator-ui-components/src/components/WfoTable/WfoTableWithFilter/updateQueryString.ts
packages/orchestrator-ui-components/src/components/WfoTable/utils/tableUtils.ts
packages/orchestrator-ui-components/src/hooks/useDataDisplayParams.ts
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/pages/metadata/WfoProductBlocksPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoProductsPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoResourceTypesPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoWorkflowsPage.tsx

#478 
#543 
- Replace searchbar with a generic one
- Adds query string updater helper
- Renames esQueryString to queryString

478 filter query frontend update function

---

apps/wfo-ui-surf/pages/tasks/new/[taskName].tsx
apps/wfo-ui-surf/pages/workflows/new/[workflowName].tsx
apps/wfo-ui/pages/tasks/new/[taskName].tsx
apps/wfo-ui/pages/workflows/new/[workflowName].tsx
packages/orchestrator-ui-components/src/graphqlQueries/index.ts
packages/orchestrator-ui-components/src/graphqlQueries/processStepsQuery.ts
packages/orchestrator-ui-components/src/pages/processes/WfoStartProcessPage.tsx
packages/orchestrator-ui-components/src/types/types.ts

https://github.com/workfloworchestrator/orchestrator-ui/issues/383

383 Real process steps in start process screen

---

.changeset/lemon-guests-explain.md
apps/wfo-ui-surf/package.json
apps/wfo-ui-surf/translations/translationsProvider.tsx
apps/wfo-ui/package.json
apps/wfo-ui/translations/translationsProvider.tsx
package.json
packages/eslint-config-custom/package.json
packages/jest-config/package.json
packages/orchestrator-ui-components/package.json
packages/orchestrator-ui-components/src/components/WfoForms/formFields/SubscriptionField.tsx
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoPageHeader/WfoPageHeader.tsx
yarn.lock

I have Yolo'd this a bit and update everything except uniforms, this includes
- Typescript from 4.x to 5.3.3
- NextJs from 13.x o 14.0.4
It all seems to work!

519 Update yarn packages to latest versions

---

packages/orchestrator-ui-components/src/components/WfoProcessList/WfoProcessesList.tsx
packages/orchestrator-ui-components/src/graphqlQueries/processListQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/productBlocksQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/productsQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/resourceTypesQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/workflows/workflowsQuery.ts
packages/orchestrator-ui-components/src/pages/metadata/WfoProductBlocksPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoResourceTypesPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoWorkflowsPage.tsx

Enables the query filter-parameter on all graphql queries returning list results

Enables the query filter-parameter on all graphql queries

---

apps/wfo-ui-surf/pages/index.tsx
packages/orchestrator-ui-components/src/components/WfoError/WfoError.stories.tsx
packages/orchestrator-ui-components/src/components/WfoError/WfoError.tsx
packages/orchestrator-ui-components/src/components/WfoError/index.ts
packages/orchestrator-ui-components/src/components/WfoProcessList/WfoProcessesList.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscription.tsx
packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/WfoSubscriptionsList.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTableWithFilter/WfoTableWithFilter.tsx
packages/orchestrator-ui-components/src/components/WfoTable/utils/mapSortableAndFilterableValuesToTableColumnConfig.ts
packages/orchestrator-ui-components/src/components/index.ts
packages/orchestrator-ui-components/src/hooks/useQueryWithGraphql.ts
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/pages/metadata/WfoProductBlocksPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoProductsPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoResourceTypesPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoWorkflowsPage.tsx
packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetail.tsx
packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetailPage.tsx
packages/orchestrator-ui-components/src/pages/processes/WfoStartProcessPage.tsx

Handles the situation where an error occurs when retrieving data from graphql or during form rendering for example when the eduVPN is inactive

579 error handling graphql

---

apps/wfo-ui-surf/components/WfoAvatar/WfoAvatar.tsx
apps/wfo-ui-surf/components/WfoAvatar/styles.ts
apps/wfo-ui-surf/components/WfoServiceTicketDetailPage/WfoServiceTicket.tsx
apps/wfo-ui-surf/components/WfoServiceTicketDetailPage/WfoServiceTicketGeneral.tsx
apps/wfo-ui-surf/components/WfoServiceTicketDetailPage/WfoServiceTicketNotificationLog.tsx
apps/wfo-ui-surf/translations/en-GB.json
apps/wfo-ui-surf/translations/nl-NL.json
apps/wfo-ui-surf/types/types.ts
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoStepStatusIcon/WfoStepStatusIcon.tsx
packages/orchestrator-ui-components/src/components/index.ts
packages/orchestrator-ui-components/src/icons/WfoBell.tsx
packages/orchestrator-ui-components/src/icons/WfoContactEnvelopeFill.tsx
packages/orchestrator-ui-components/src/icons/index.ts
packages/orchestrator-ui-components/src/utils/date.ts

Added the page for the Notification Log tab in the service ticket details.

Notification Log tab page

---

apps/wfo-ui-surf/configuration/configuration.ts
apps/wfo-ui/configuration/configuration.ts
packages/orchestrator-ui-components/src/components/WfoForms/formFields/SubscriptionField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/utils.spec.ts
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/WfoStartCreateWorkflowButtonComboBox.tsx
packages/orchestrator-ui-components/src/components/WfoStartTaskButtonComboBox/WfoStartTaskButtonComboBox.tsx
packages/orchestrator-ui-components/src/contexts/OrchestratorConfigContext.tsx
packages/orchestrator-ui-components/src/graphqlQueries/customersQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/subscriptionsDropdownOptionsQuery.ts
packages/orchestrator-ui-components/src/graphqlQueries/workflows/workflowsQueryForDropdownList.ts
packages/orchestrator-ui-components/src/hooks/surf/useGetSubscriptionDropdownOptions.ts
packages/orchestrator-ui-components/src/hooks/surf/useIsTaggedPort.ts
packages/orchestrator-ui-components/src/hooks/useOrchestratorConfig.ts
packages/orchestrator-ui-components/src/hooks/useQueryWithGraphql.ts
packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetailPage.tsx
packages/orchestrator-ui-components/src/pages/processes/WfoStartProcessPage.tsx
packages/orchestrator-ui-components/src/pages/tasks/tabConfig.ts
packages/orchestrator-ui-components/src/types/types.ts

This fixes a few things:
- An error in filtering subscriptions that caused the subscriptionDropdown list to be empty
- Removes pagination form the subscriptions dropdown list
- Remove fetchInterval from context preventing strange rerenders

619 data fetching bug

---

packages/orchestrator-ui-components/src/pages/startPage/WfoStartPage.tsx
packages/orchestrator-ui-components/src/pages/tasks/tabConfig.ts
packages/orchestrator-ui-components/src/pages/workflows/tabConfig.ts

* added some missing statuses to the task and workflow list tables
* added some statuses to the startpage summary cards

628 add status 2 processlist page

---

apps/wfo-ui-surf/pages/_app.tsx

Introduced changes in wfo-ui were not applied to wfo-ui-surf

Applies same settings in wfo-ui-surf app as wfo-ui app

---

packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoPageHeader/WfoPageHeader.tsx
packages/orchestrator-ui-components/src/icons/WfoSideMenu.stories.tsx
packages/orchestrator-ui-components/src/icons/WfoSideMenu.tsx
packages/orchestrator-ui-components/src/icons/index.ts

* Add new icon, and used in header component.
* Placement in front of breadcrumb still te be done

Add new icon, and used in header component

---

.changeset/config.json
.changeset/shaggy-squids-kick.md

Updates config for Changesets:
- ignores the apps in the turborepo
- corrects existing changeset

Updates Changeset config

---

packages/orchestrator-ui-components/src/components/WfoForms/formFields/SplitPrefix.tsx

Improved the selectable prefixlengths in dropdown

---

.changeset/ten-carrots-relax.md
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/WfoCopyright.tsx
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/WfoSidebar.tsx
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/styles.ts

Copyright  in left bottom corner of sidebar
Use year is dynamically generated from date

added copyright to sidebar

---

apps/wfo-ui-surf/components/WfoBadges/WfoImpactLevelBadge.tsx
apps/wfo-ui-surf/components/WfoServiceTicketDetailPage/WfoImpactTable.tsx
apps/wfo-ui-surf/components/WfoServiceTicketDetailPage/WfoImpactedCustomersTable.tsx
apps/wfo-ui-surf/components/WfoServiceTicketDetailPage/WfoImsCircuitsTable.tsx
apps/wfo-ui-surf/components/WfoServiceTicketDetailPage/utils.ts
apps/wfo-ui-surf/configuration/configuration.ts
apps/wfo-ui-surf/contexts/SurfConfigContext.tsx
apps/wfo-ui-surf/types/types.ts

fixes https://github.com/workfloworchestrator/orchestrator-ui-library/issues/700

Fix for impact table expanding row and show inform customers

---

.changeset/smooth-walls-laugh.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/ContactPersonNameField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/SummaryField.tsx

- check if row is string before trying .includes.
- change incorrect default customerKey in ContactPersonName field
Fixes: #723

723: Fix SummaryField .includes is not a function

---

.changeset/tame-horses-drive.md
packages/orchestrator-ui-components/src/graphqlQueries/processDetailQuery.ts

- `form` changed from graphql type to a JSON in the backend.

Fix ProcessDetailQuery by removing form subfields

---

packages/orchestrator-ui-components/src/components/WfoProcessList/WfoProcessesList.tsx
packages/orchestrator-ui-components/src/components/WfoProcessList/processListObjectMappers.ts
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/pages/tasks/WfoTasksListPage.tsx

Update 'productTag' field to 'tag'

---

.changeset/bright-adults-wave.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/CustomerField.tsx

721: Fix customer select not being disabled

---

.changeset/breezy-cherries-press.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/ContactPersonNameField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListSelectField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/SelectField.tsx

Fix errors caused by uniforms connectField

---

packages/orchestrator-ui-components/src/components/WfoSettings/WfoModifySettings.tsx
packages/orchestrator-ui-components/src/components/WfoSettings/WfoResetTextSearchIndexButton.tsx
packages/orchestrator-ui-components/src/components/WfoSettings/index.ts
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/rtk/endpoints/settings.ts

added reset button on settings page

---

packages/orchestrator-ui-components/src/pages/startPage/WfoStartPage.tsx

#702 
Cannot sort on immutable data, speading the array before sorting

702 Fixes error rendering productsSummaryCard

---

.changeset/nice-parents-crash.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/SelectField.tsx
packages/orchestrator-ui-components/src/pages/processes/WfoStartProcessPage.tsx

closes https://github.com/workfloworchestrator/orchestrator-ui-library/issues/820

820: Bug removing existing values. Allows sending null values

---

.changeset/perfect-moose-wave.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/deprecated/ImsPortIdField.tsx

#919 
- Clears port when changing node

919 fix select port node sp

---

.changeset/loud-zebras-walk.md
CHANGELOG.md
README.md
packages/eslint-config-custom/LICENSE.txt
packages/eslint-config-custom/README.md
packages/eslint-config-custom/package.json
packages/jest-config/LICENSE.txt
packages/jest-config/README.md
packages/jest-config/package.json
packages/orchestrator-ui-components/CHANGELOG.md
packages/orchestrator-ui-components/LICENSE.txt
packages/orchestrator-ui-components/README.md
packages/orchestrator-ui-components/package.json
packages/tsconfig/LICENSE.txt
packages/tsconfig/README.md
packages/tsconfig/package.json

Issue https://github.com/workfloworchestrator/orchestrator-ui-library/issues/659
Adds fields and files that are used to display on NPM package pages like link backs to the repo and general information

659 npm documentation

---

.changeset/tame-glasses-bow.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/utils.spec.ts
packages/orchestrator-ui-components/src/components/WfoJsonCodeBlock/WfoJsonCodeBlock.tsx
packages/orchestrator-ui-components/src/components/WfoJsonCodeBlock/styles.ts
packages/orchestrator-ui-components/src/components/WfoKeyValueTable/WfoValueCell.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscription.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionGeneral.tsx
packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/WfoSubscriptionsList.tsx
packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/subscriptionResultMappers.ts
packages/orchestrator-ui-components/src/components/WfoTable/WfoInlineJson/WfoInlineJson.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoInlineJson/index.ts
packages/orchestrator-ui-components/src/components/WfoTable/index.ts
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/rtk/endpoints/subscriptionDetail.ts
packages/orchestrator-ui-components/src/rtk/endpoints/subscriptionList.ts
packages/orchestrator-ui-components/src/types/types.ts
packages/orchestrator-ui-components/src/utils/getDefaultTableConfig.ts

#332 
- Adds metadata column to the subscription list table (metadata is of type object)
- Adds metadata to the row detail view of the table
- Adds metadata section to subscription detail page

332 metadata subscriptionlist subscriptiondetail

---

.changeset/violet-camels-watch.md
packages/orchestrator-ui-components/src/components/WfoJsonCodeBlock/WfoJsonCodeBlock.tsx
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoWorkflowStepList/WfoStepListHeader.tsx
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoWorkflowStepList/WfoWorkflowStepList.tsx
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoWorkflowStepList/styles.ts
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetailPage.tsx
packages/orchestrator-ui-components/src/rtk/endpoints/processDetail.ts
packages/orchestrator-ui-components/src/types/types.ts
packages/orchestrator-ui-components/src/utils/getProductNamesFromProcess.spec.ts

#863 
- Adds Traceback on process detail page

863 Adds traceback on the process detail page

---

.changeset/grumpy-sloths-run.md
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoPageHeader/WfoPageHeader.tsx
packages/orchestrator-ui-components/src/contexts/OrchestratorConfigContext.tsx
packages/orchestrator-ui-components/src/hooks/index.ts
packages/orchestrator-ui-components/src/hooks/useGetOrchestratorConfig.ts
packages/orchestrator-ui-components/src/rtk/slices/orchestratorConfig.ts
packages/orchestrator-ui-components/src/types/types.ts

Adds the feature toggles to the configuration so they can are used at runtime instead of buildtime

941: Add theme and websocket toggles to config

---

.changeset/poor-meals-check.md
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoTraceback/WfoTraceback.tsx
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoTraceback/index.ts
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoTraceback/styles.ts
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoWorkflowStepList/WfoWorkflowStepList.tsx
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json

863 Extracts a traceback component and adds title for that section

---

.changeset/dry-tables-bathe.md
packages/orchestrator-ui-components/src/pages/startPage/WfoStartPage.tsx

- uses preferred_username to filter for workflows
- removes hardcoded todo :)

Uses username instead of name to get the my-workflow data

---

packages/orchestrator-ui-components/src/components/WfoForms/UserInputForm.tsx

closes https://github.com/workfloworchestrator/orchestrator-ui-library/issues/1063

Fix for IP Peer worklows

---

.changeset/lovely-meals-sleep.md
packages/orchestrator-ui-components/src/pages/startPage/queryVariables.ts
packages/orchestrator-ui-components/src/rtk/endpoints/productsSummary.ts

#1086 
Adds extra filter to the query used in the summary card showing the total number of products

1086 total number of products fix

---

.changeset/violet-olives-drop.md
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoInUseByRelations.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionDetailTree.tsx

#1085 
Filters out current subscription from the list of related subscriptions

1085 related subscriptions filtered

---

.changeset/cold-sloths-repair.md
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/WfoSidebar.tsx
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/index.ts
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/utils/index.ts
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/utils/menuItemIsAllowed.spec.ts
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/utils/menuItemIsAllowed.ts

#916 
Small refactor on the filtering of menu items

916 menu item override refactor

---

packages/orchestrator-ui-components/src/components/WfoForms/CreateForm.tsx
packages/orchestrator-ui-components/src/components/WfoForms/UserInputForm.tsx
packages/orchestrator-ui-components/src/components/WfoForms/UserInputFormWizard.tsx
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/pages/processes/WfoStartProcessPage.tsx
packages/orchestrator-ui-components/src/types/forms.ts

Use FormNotCompleteResponse meta for styling FormPage submit buttons

---

.changeset/tame-kings-hunt.md
package-lock.json
packages/orchestrator-ui-components/src/components/WfoForms/formFields/deprecated/ImsPortIdField.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscription.tsx

This PR adds a notice when - in a modify workflow - a previously selected subscription with a node doesn't exist anymore.

1124 port select bug

---

.changeset/eighty-hats-speak.md
packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetailPage.tsx
packages/orchestrator-ui-components/src/rtk/api.ts
packages/orchestrator-ui-components/src/rtk/endpoints/processDetail.ts
packages/orchestrator-ui-components/src/rtk/endpoints/processList.ts
packages/orchestrator-ui-components/src/rtk/endpoints/streamMessages.ts

https://github.com/workfloworchestrator/orchestrator-ui-library/issues/1160

1160 websocket processdetail

---

.changeset/thick-turtles-know.md
packages/orchestrator-ui-components/src/components/WfoForms/UserInputForm.tsx
packages/orchestrator-ui-components/src/components/WfoForms/UserInputFormWizard.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoInSyncField.tsx
packages/orchestrator-ui-components/src/components/confirmationDialog/WfoConfirmationDialog.tsx
packages/orchestrator-ui-components/src/contexts/ConfirmationDialogProvider.tsx
packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetail.tsx
packages/orchestrator-ui-components/src/pages/tasks/WfoTasksListPage.tsx

Refactored and rearranged a bit to make it clearer (to me at least :)) Let me know if I missewd something

1052: Refactors confirmation dialag and changes order on pageleave

---

.changeset/dirty-radios-press.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListAddField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListDelField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListItemField.tsx

To startof any discussions: 
- I have taken a lot of liberty and css hacks here but it's because it's uniforms and doing it more clean would take a lot more time and introduces uncertainty. 
- I want Floris to test this well because i'm not fully aware off all scenarios. Changes may be incoming based on what he finds I guess.

1217 list field

---

.changeset/many-oranges-roll.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListAddField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/ListDelField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/deprecated/VlanField.tsx

#1295 
- Partial rollback of refactor introduced in PR #1242
- Fixes one list item shown above max allowed

1295 forms lists removing items

---

.changeset/rare-rats-return.md
packages/orchestrator-ui-components/src/rtk/endpoints/streamMessages.ts

#822 
Removing the disconnect logic from frontend, since this is not working as expected when the browser goes into suspended state.

822 Removes the debounce mechanism causing the disconnects

---

.changeset/neat-poems-rest.md
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoRelatedSubscriptions.tsx

906 fix loading state related subscriptions

---

.changeset/nervous-ghosts-watch.md
packages/orchestrator-ui-components/src/components/WfoError/WfoError.tsx
packages/orchestrator-ui-components/src/components/WfoProcessList/WfoProcessesList.tsx
packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/WfoSubscriptionsList.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTableWithFilter/WfoTableWithFilter.tsx
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/pages/metadata/WfoProductBlocksPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoProductsPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoResourceTypesPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoTasksPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoWorkflowsPage.tsx
packages/orchestrator-ui-components/src/rtk/api.ts
packages/orchestrator-ui-components/src/rtk/endpoints/subscriptionList.ts
packages/orchestrator-ui-components/src/rtk/utils.ts
packages/orchestrator-ui-components/src/rtk/wfoGraphqlRequestBaseQuery.ts

Search bar visible when having errors in WfoTableWithFilter

---

.changeset/four-worms-chew.md
packages/orchestrator-ui-components/src/components/WfoError/WfoError.tsx
packages/orchestrator-ui-components/src/rtk/endpoints/subscriptionList.ts
packages/orchestrator-ui-components/src/rtk/utils.ts

Fixed a bug where error always shows and improved error mapper.

Fix bug new error presentation

---

.changeset/many-comics-pull.md
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/WfoSidebar.tsx

see https://github.com/workfloworchestrator/orchestrator-ui-library/issues/1362

Changed order of side menu

---

.changeset/slow-files-yawn.md
packages/orchestrator-ui-components/src/components/WfoRadioDropdown/WfoRadioDropdown.tsx
packages/orchestrator-ui-components/src/components/WfoRadioDropdown/index.ts
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoProcessesTimeline.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/utils/utils.ts
packages/orchestrator-ui-components/src/components/index.ts
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/types/types.ts

Add sorting for subscription details workflows tab

---

.changeset/shiny-ghosts-marry.md
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/WfoMultilineCell.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/WfoTruncateCell.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/index.ts

#1363 
Adds:
WfoMultilineCell
WfoTruncateCell

1363 Adds WfoMultilineCell and WfoTruncateCell

---

.changeset/quick-carrots-grin.md
packages/orchestrator-ui-components/src/components/WfoTable/WfoAdvancedTable/WfoAdvancedTable.tsx

#1363 
Fixes the labels of the table settings modal

1363 Fixes the labels of the table settings modal

---

.changeset/sweet-wasps-look.md
packages/orchestrator-ui-components/src/components/WfoStartButton/WfoStartTaskComboBox.tsx
packages/orchestrator-ui-components/src/components/WfoStartButton/WfoStartWorkflowComboBox.tsx
packages/orchestrator-ui-components/src/rtk/endpoints/startOptions.ts

Added sorting for new tasks and workflow dropdowns

---

.changeset/smooth-donuts-kneel.md
packages/orchestrator-ui-components/src/hooks/useWfoSession.ts
packages/orchestrator-ui-components/src/rtk/api.ts
packages/orchestrator-ui-components/src/rtk/wfoGraphqlRequestBaseQuery.ts

#1423 
- Handles not_authenticated errors from graphql endpoints
- Adds accessTokenExpiresAt and refreshTokenExpiresAt to WfoSession

1423 Handles not_authenticated errors from graphql endpoints

---

.changeset/nervous-cows-invent.md
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/WfoGroupedTable/useGroupedTableConfig.tsx

#1494 
Introduces refs for notifyParent and groups to prevent the useEffect loop

1494 - Fixes useEffect loop

---

.changeset/witty-pens-invent.md
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoWorkflowStepList/WfoStepListHeader.tsx
packages/orchestrator-ui-components/src/components/WfoWorkflowSteps/WfoWorkflowStepList/WfoWorkflowStepList.tsx
packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetailPage.tsx

#1451 
Disables the subscription delta button when the process is running

1451 Disables the subscription delta button when the process is running

---

.changeset/odd-donuts-count.md
packages/orchestrator-ui-components/src/pages/processes/WfoProcessDetailPage.tsx
packages/orchestrator-ui-components/src/pages/processes/WfoStartProcessPage.tsx
packages/orchestrator-ui-components/src/rtk/endpoints/index.ts
packages/orchestrator-ui-components/src/rtk/endpoints/metadata/workflows.ts

#1504 
Resolves task names and workflow names into the description text from the metadata endpoint, making the titles more human-readable

#1504 pretty workflow task names

---

.changeset/chilly-rules-begin.md
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionActions/WfoSubscriptionActionExpandableMenuItem.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionActions/WfoSubscriptionActions.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionActions/index.ts
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionActions/styles.ts
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json

#1503
When an action is unavailable it becomes and expandable menu item listing subscription-links preventing that action

#1503 locked by subscriptions links

---

packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionActions/WfoSubscriptionActionExpandableMenuItem.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionActions/styles.ts

#1540 
- Applies rounded corners on the hover effect
- Fixes mouse pointer to not show clickable when the disabled action menu item is not expandable

#1503 Applies rounded corners and fixes mouse pointer hover state

---

.changeset/twelve-crews-return.md
packages/orchestrator-ui-components/src/components/WfoSubscriptionsList/WfoSubscriptionsList.tsx

#1556 
Adds inline note edit for subscription list page

1556 Adds inline note edit for subscription list page

---

.changeset/happy-rivers-attend.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/BoolFieldStyling.ts

#1577 
Fixes uncheckable checkbox (only the label was clickable)

1577 Fixes uncheckable checkbox (only the label was clickable)

---

.changeset/lazy-suns-love.md
packages/orchestrator-ui-components/src/components/WfoSubscription/styles.ts

1552 Remove last line of workflow timeline card

---

.changeset/wise-files-study.md
packages/orchestrator-ui-components/src/components/WfoForms/AutoFieldLoader.tsx

- fixes summary field with pydantic-forms 1.1.1

Add summary field to Object in AutoFieldLoader

---

.changeset/six-gifts-change.md
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/WfoExpandedRow.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/WfoTableDataRows.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/index.ts

#1569
Some non-functional tweaks on the table components: Adds classNames and adds a Fragment component in a mapper function

1569 table adjustments

---

.changeset/curly-squids-design.md
packages/orchestrator-ui-components/src/components/WfoForms/UserInputForm.tsx
packages/orchestrator-ui-components/src/pages/processes/WfoStartProcessPage.tsx

Allow Create LIR prefixes workflow to start with pre-filled variables

---

.changeset/perfect-laws-argue.md
packages/orchestrator-ui-components/src/components/WfoTable/utils/tableUtils.spec.ts
packages/orchestrator-ui-components/src/components/WfoTable/utils/tableUtils.ts

1732: Adds an asteriks if the query is a single word without special character

---

.changeset/late-terms-admire.md
apps/storybook/index.html
package-lock.json
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/pages/metadata/WfoTasksPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/WfoWorkflowsPage.tsx
packages/orchestrator-ui-components/src/pages/metadata/taskListObjectMapper.ts
packages/orchestrator-ui-components/src/pages/metadata/workflowListObjectMapper.ts
packages/orchestrator-ui-components/src/rtk/endpoints/metadata/tasks.ts
packages/orchestrator-ui-components/src/rtk/endpoints/metadata/workflows.ts
packages/orchestrator-ui-components/src/types/types.ts
packages/orchestrator-ui-components/src/utils/getDefaultTableConfig.ts

Reverts workfloworchestrator/orchestrator-ui-library#1740

Revert "added Id column to metadata workflow and task table"

---

.changeset/empty-rats-camp.md
README.md
packages/orchestrator-ui-components/src/components/WfoBadges/WfoVersionIncompatibleBadge/WfoVersionIncompatibleBadge.stories.tsx
packages/orchestrator-ui-components/src/components/WfoBadges/WfoVersionIncompatibleBadge/WfoVersionIncompatibleBadge.tsx
packages/orchestrator-ui-components/src/components/WfoBadges/WfoVersionIncompatibleBadge/index.ts
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoPageHeader/WfoPageHeader.tsx
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/messages/nl-NL.json
packages/orchestrator-ui-components/src/types/types.ts
packages/orchestrator-ui-components/src/utils/compareVersions.spec.ts
packages/orchestrator-ui-components/src/utils/compareVersions.ts
version-compatibility.json

Show error badge in navigation header when versions mismatch

---

.changeset/wicked-ladybugs-attack.md
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/WfoDragHandler.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/WfoTable.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/styles.ts

1707 Improve resizing of table columns, make WfoTable width auto

---

.changeset/large-peas-relate.md
packages/orchestrator-ui-components/src/components/WfoSummary/WfoActiveWorkflowsSummaryCard.tsx
packages/orchestrator-ui-components/src/components/WfoSummary/WfoFailedTasksSummaryCard.tsx
packages/orchestrator-ui-components/src/components/WfoSummary/WfoLatestActiveSubscriptionsSummaryCard.tsx
packages/orchestrator-ui-components/src/components/WfoSummary/WfoLatestOutOfSyncSubscriptionSummaryCard.tsx
packages/orchestrator-ui-components/src/components/WfoSummary/WfoMyWorkflowsSummaryCard.tsx
packages/orchestrator-ui-components/src/components/WfoSummary/WfoProductsSummaryCard.tsx
packages/orchestrator-ui-components/src/components/WfoSummary/WfoSummaryCard.tsx
packages/orchestrator-ui-components/src/components/WfoSummary/WfoSummaryCardHeader/WfoSummaryCardHeader.tsx

Improve summary cards loading states

---

.changeset/fair-llamas-knock.md
package-lock.json
packages/orchestrator-ui-components/package.json

Updates required peer dependencies to NextJs 14.2.25 (CVE-2025-29927)

Updates required peer dependencies to NextJs 14.2.25 (CVE-2025-29927)

---

.changeset/yellow-houses-remember.md
packages/orchestrator-ui-components/src/components/WfoInlineEdit/WfoInlineEdit.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/WfoToolTip.tsx
packages/orchestrator-ui-components/src/components/WfoTable/WfoTable/styles.ts

#1751
Makes width of the inline not edit field flexible

1751 Makes width of the inline note edit field flexible

---

.changeset/tricky-schools-greet.md
packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoSidebar/styles.ts

Fix for the thin gray line in the sidebar that went beyond settings.

Fix cosmetic issue with side bar

---

.changeset/tall-chicken-type.md
packages/orchestrator-ui-components/src/components/WfoSettings/WfoModifySettings.tsx
packages/orchestrator-ui-components/src/configuration/policy-resources.ts

#1844 
Adds isAllowed policy check to the start-stop-engine button section (the whole card including white space)

1844 Adds isAllowed policy check to the start-stop-engine button

---

package-lock.json

Reverts the downgrade from https://github.com/workfloworchestrator/orchestrator-ui-library/commit/9eb223ee3bb1f95826dcaa8c79ef257c1afaee4d#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519

Reverts downgrade of nextjs

---

.changeset/thirty-coins-battle.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/utils.ts
packages/orchestrator-ui-components/src/rtk/endpoints/subscriptionsDropdownOptions.ts
packages/orchestrator-ui-components/src/types/types.ts

Related orchestrator-core PR: https://github.com/workfloworchestrator/orchestrator-core/pull/922

Remove inUseByRelations field from query SubscriptionDropdownOptions

---

.changeset/nervous-beds-type.md
packages/orchestrator-ui-components/src/components/WfoBadges/WfoProcessStatusBadge/WfoProcessStatusBadge.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoProcessesTimeline.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/styles.ts

Fix layout issue with workflows on subscription detail page

---

.changeset/beige-vans-arrive.md
packages/orchestrator-ui-components/src/rtk/endpoints/startOptions.ts

related: https://github.com/workfloworchestrator/orchestrator-ui-library/issues/1930

Add product tag to workflow options query

---

.changeset/eighty-oranges-travel.md
package-lock.json
package.json
packages/orchestrator-ui-components/src/components/WfoBadges/WfoWorkflowTargetBadge/WfoWorkflowTargetBadge.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/WfoSubscriptionActions/WfoSubscriptionActions.tsx
packages/orchestrator-ui-components/src/components/WfoSubscription/utils/utils.ts
packages/orchestrator-ui-components/src/rtk/endpoints/metadata/tasks.ts
packages/orchestrator-ui-components/src/rtk/endpoints/metadata/workflows.ts
packages/orchestrator-ui-components/src/rtk/endpoints/startOptions.ts
packages/orchestrator-ui-components/src/types/types.ts
version-compatibility.json

Part of https://github.com/orgs/workfloworchestrator/projects/7/views/1?pane=issue&itemId=104726201&issue=workfloworchestrator%7Corchestrator-ui-library%7C1843
Update frontend to work with isTask validation workflow

Update target validation to isTask

---

.changeset/perfect-radios-report.md
packages/orchestrator-ui-components/src/components/WfoSummary/WfoMyWorkflowsSummaryCard.tsx

Add quote to make the filter work

2001 fix filter of summarycard

---

packages/orchestrator-ui-components/src/components/WfoPageTemplate/WfoPageHeader/WfoHamburgerMenu.tsx
packages/orchestrator-ui-components/src/components/WfoSettings/WfoAoStackStatus.tsx
packages/orchestrator-ui-components/src/contexts/OrchestratorConfigContext.tsx
packages/orchestrator-ui-components/src/icons/WfoChartBar.tsx
packages/orchestrator-ui-components/src/icons/index.ts
packages/orchestrator-ui-components/src/messages/en-GB.json
packages/orchestrator-ui-components/src/pages/settings/WfoSettingsPage.tsx
packages/orchestrator-ui-components/src/types/types.ts

AO stack status menu and settings item

---

.changeset/easy-crews-fry.md
packages/orchestrator-ui-components/src/components/WfoForms/formFields/SummaryField.tsx
packages/orchestrator-ui-components/src/components/WfoForms/formFields/SummaryFieldStyling.ts
packages/orchestrator-ui-components/src/components/WfoForms/formFields/index.ts
packages/orchestrator-ui-components/src/components/WfoPydanticForm/fields/WfoSummary.tsx

Fixed summaryForm styles + dark theme
